version: '3.8'

services:
  server:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    container_name: router
    links:
      - mongodb_container
    ports:
      - 8080:4000
    depends_on: 
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    container_name: mongo_qa
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    # command: mongod --auth

volumes:
  mongodb_data_container:
