version: '3.8'

services:
  server:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    container_name: router
    environment:
      PORT: ${PORT}
      URL: ${URL}
    links:
      - mongodb_container
    ports:
      - 8080:4000
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    container_name: mongo_qa
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    command: mongod --auth

volumes:
  mongodb_data_container:
